### ISSUE TITLE
Passing arguments to the docker run command

### ISSUE THREAD

**Issue by mogthesprog** [GoogleCloudPlatform/container-structure-test#70]
When we're using the docker driver, is there anyway to currently pass arguments to the docker run command? for example if i have a container that needs extra capabilites, or you want to add a volume mount to test a command with some custom config?

**Comment by mogthesprog** [comment]
I'm actually happy to have a go at this, but wanted to check if you'd thought about how you might do this? 

Use case for us is we have an auditd container that contains some audisp plugins we'd like to test, which needs some extra privileges in order to run successfully.

I'm wondering whether we could add a `dockerRunOpts` top-level field to test `yaml`? that might allow you to set global docker run options. Something the below. We wouldn't need to support all the options really, since some of them are constructued by the driver at runtime.

```Go
type dockerRunOpts struct {
  Mounts []docker.Mount
  // by default drop all capabilites
  Capabilites []string
  privileged bool
}
```

and the yaml might look like:

```yaml
dockerRunOpts:
  mounts:
    -  source: /tmp/beans
        destination /tmp/cheese
        readWrite: false
  privileged: false
  capabilities:
    - SYS_ADMIN
```

**Comment by nkubala** [comment]
Hey @mogthesprog, thanks for filing. I think I'm ok with with the general design here, seems like there's enough desire for run options here to warrant taking a stab at it. The one change I think we'll have to make to the UX is probably embedding the `driver` flag into the `yaml`, so that it's a little more explicit when you specify a `dockerRunOpts` field that it'll be used with the `docker` driver, or that it will be ignored if you specify a different driver.

As far as fields in the `dockerRunOpts`, I'd say the 3 you have in there right now are fine, we might want to consider adding support for networking options as well.

**Comment by mogthesprog** [comment]
so maybe something like this? also means if we end up supporting a different container driver then it's a little more generic.

```yaml
containerRunOpts:
  driver: docker
  mounts:
    -  source: /tmp/beans
        destination /tmp/cheese
        readWrite: false
  privileged: false
  capabilities:
    - SYS_ADMIN
```
